# Generated by Django 6.1 on 2026-08-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravaah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/'),
        ),
    ]
